# Generated by Django 4.2 on 2023-05-01 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('orders', '0004_salesorder_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.email'),
        ),
    ]
